name: Bicep Module Publish

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # get repo with tags

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Publish Bicep modules
      run: .github/publish-modules.sh